server:
  port: 8082

spring:
  application:
    name: MoviesPlatform
  profiles:
    active: local

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
      - org.springframework.boot.autoconfigure.data.redis.RedisReactiveAutoConfiguration

  # Database Configuration
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/movies_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:12345}
    hikari:
      minimum-idle: 3
      maximum-pool-size: 6
      idle-timeout: 30000
      max-lifetime: 2000000
      connection-timeout: 60000

  # JPA and Hibernate configurations
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  # Liquibase Configuration
  liquibase:
    change-log: classpath:liquibase/changelog-master.yml
    enabled: true

  # MAIL KONFİQURASİYASI
  mail:
    host: smtp.gmail.com
    port: 587
    username: aslanli.mobil9@gmail.com
    password: "ozhpghbaugihbfxx"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  # MinIO Konfiqurasiyası
  minio:
    url: http://localhost:9000
    access-key: minioadmin
    secret-key: minioadmin

  # File Upload Configuration
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB

minio:
  bucket-name: movie-videos

# Custom Application Parametrlər
application:
  security:
    jwt:
      secret-key: ${JWT_SECRET:secure-and-very-long-secret-key-for-jwt-at-least-32-chars}
      expiration-ms: 86400000 # 1 gün

# Swagger/OpenAPI Configuration
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: alpha

# Logging Configuration
logging:
  level:
    root: info
    org.example.moviesplatform: debug
    org.hibernate.SQL: info